/// Compiles Arcis intermediate-representation files (.arcis.ir) into the binary
/// circuit bytecode (.arcis) that arcium-macros proc-macros require at build time.
///
/// Run from the veilvault/ workspace root:
///   cargo run -p circuit-builder
///
/// The .arcis.ir files in build/ are generated by `cargo build -p encrypted-ixs`.
/// This tool performs the second compilation step (IR → binary) that the Arcium CLI
/// normally handles, enabling offline builds without the arcium CLI installed.
fn main() {
    let circuits = [
        "build/init_position",
        "build/add_collateral",
        "build/remove_collateral",
        "build/add_borrow",
        "build/remove_borrow",
        "build/check_health",
    ];

    let mut success = 0;
    let mut failed = 0;

    for circuit in &circuits {
        let ir_path = format!("{}.arcis.ir", circuit);
        if !std::path::Path::new(&ir_path).exists() {
            eprintln!("SKIP  {} — .arcis.ir not found (run `cargo build -p encrypted-ixs` first)", circuit);
            failed += 1;
            continue;
        }

        match arcis_compiler::compile::compile_and_write(circuit) {
            Ok(()) => {
                println!("OK    {}.arcis", circuit);
                success += 1;
            }
            Err(e) => {
                eprintln!("FAIL  {} — {}", circuit, e);
                failed += 1;
            }
        }
    }

    println!("\n{} compiled, {} failed/skipped", success, failed);
    if failed > 0 {
        std::process::exit(1);
    }
}
